// Set to true to use demo mode without backend, false for real MongoDB + Express
export const DEMO_MODE = false;

// Demo user accounts
export const DEMO_USERS = {
  student: {
    uid: 'demo-student-001',
    email: 'student@demo.com',
    displayName: 'Alex Student',
    role: 'user',
  },
  admin: {
    uid: 'demo-admin-001',
    email: 'admin@demo.com',
    displayName: 'Admin User',
    role: 'admin',
  },
};

// Demo course data
export const DEMO_COURSES = [
  {
    id: 'course-001',
    title: 'Complete React Native Masterclass',
    description: 'Learn to build beautiful, production-ready mobile apps with React Native from scratch. This comprehensive course covers everything from basics to advanced topics including navigation, state management, API integration, animations, and deployment to both iOS and Android app stores.',
    instructor: 'Sarah Johnson',
    category: 'Mobile Development',
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600',
    duration: '24h 30m',
    difficulty: 'Intermediate',
    rating: 4.8,
    reviewCount: 1247,
    enrolledCount: 8934,
    videoUrl: 'https://www.youtube.com/watch?v=0-S5a0eXPoc',
    lessons: [
      { title: 'Introduction to React Native', videoUrl: 'https://www.youtube.com/watch?v=0-S5a0eXPoc', duration: '15:30' },
      { title: 'Setting Up Development Environment', videoUrl: 'https://www.youtube.com/watch?v=obH0Po_RGBk', duration: '22:15' },
      { title: 'Core Components & Styling', videoUrl: 'https://www.youtube.com/watch?v=ur6I5m2nTvk', duration: '35:40' },
      { title: 'Navigation with React Navigation', videoUrl: 'https://www.youtube.com/watch?v=nQVCkqvU1uE', duration: '28:10' },
      { title: 'State Management with Context API', videoUrl: 'https://www.youtube.com/watch?v=5LrDIWkK_Bc', duration: '32:00' },
      { title: 'Working with APIs & Firebase', videoUrl: 'https://www.youtube.com/watch?v=9kRgVxULbag', duration: '45:20' },
    ],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'course-002',
    title: 'Python for Data Science & AI',
    description: 'Master Python programming for data science, machine learning, and artificial intelligence. Learn pandas, NumPy, matplotlib, scikit-learn, TensorFlow, and more through hands-on projects and real-world datasets.',
    instructor: 'Dr. Michael Chen',
    category: 'Data Science',
    thumbnail: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=600',
    duration: '36h 15m',
    difficulty: 'Beginner',
    rating: 4.9,
    reviewCount: 2156,
    enrolledCount: 15420,
    videoUrl: 'https://www.youtube.com/watch?v=rfscVS0vtbw',
    lessons: [
      { title: 'Python Basics & Setup', videoUrl: 'https://www.youtube.com/watch?v=rfscVS0vtbw', duration: '20:00' },
      { title: 'Data Types & Control Flow', videoUrl: 'https://www.youtube.com/watch?v=kqtD5dpn9C8', duration: '25:30' },
      { title: 'Introduction to NumPy', videoUrl: 'https://www.youtube.com/watch?v=QUT1VHiLmmI', duration: '30:15' },
      { title: 'Data Analysis with Pandas', videoUrl: 'https://www.youtube.com/watch?v=vmEHCJofslg', duration: '40:00' },
      { title: 'Data Visualization', videoUrl: 'https://www.youtube.com/watch?v=UO98lJQ3QGI', duration: '28:45' },
    ],
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'course-003',
    title: 'Advanced JavaScript & TypeScript',
    description: 'Deep dive into modern JavaScript ES6+ and TypeScript. Learn closures, prototypes, async/await, decorators, generics, and design patterns used by top tech companies.',
    instructor: 'Emily Rodriguez',
    category: 'Web Development',
    thumbnail: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=600',
    duration: '18h 45m',
    difficulty: 'Advanced',
    rating: 4.7,
    reviewCount: 893,
    enrolledCount: 6215,
    videoUrl: 'https://www.youtube.com/watch?v=PkZNo7MFNFg',
    lessons: [
      { title: 'Advanced Closures & Scope', videoUrl: 'https://www.youtube.com/watch?v=PkZNo7MFNFg', duration: '35:00' },
      { title: 'Prototypal Inheritance Deep Dive', videoUrl: 'https://www.youtube.com/watch?v=30CYAV6YSbk', duration: '28:20' },
      { title: 'Async Patterns & Generators', videoUrl: 'https://www.youtube.com/watch?v=vn3tm0quoqE', duration: '42:15' },
      { title: 'TypeScript Fundamentals', videoUrl: 'https://www.youtube.com/watch?v=BwuLxPH8IDs', duration: '30:00' },
    ],
    createdAt: new Date('2024-03-05'),
  },
  {
    id: 'course-004',
    title: 'UI/UX Design Fundamentals',
    description: 'Learn the principles of user interface and user experience design. Master Figma, create wireframes, prototypes, and design systems that delight users and drive conversions.',
    instructor: 'Lisa Park',
    category: 'Design',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600',
    duration: '14h 20m',
    difficulty: 'Beginner',
    rating: 4.6,
    reviewCount: 674,
    enrolledCount: 4567,
    videoUrl: 'https://www.youtube.com/watch?v=FTFaQWZBqQ8',
    lessons: [
      { title: 'Design Thinking Process', videoUrl: 'https://www.youtube.com/watch?v=FTFaQWZBqQ8', duration: '22:00' },
      { title: 'Color Theory & Typography', videoUrl: 'https://www.youtube.com/watch?v=AvgCkHrcj90', duration: '30:15' },
      { title: 'Wireframing & Prototyping', videoUrl: 'https://www.youtube.com/watch?v=c9Wg6Cb_YlU', duration: '35:40' },
    ],
    createdAt: new Date('2024-04-20'),
  },
  {
    id: 'course-005',
    title: 'Cloud Computing with AWS',
    description: 'Comprehensive AWS cloud computing course covering EC2, S3, Lambda, DynamoDB, CloudFormation, and more. Prepare for the AWS Solutions Architect certification exam.',
    instructor: 'James Wilson',
    category: 'Cloud Computing',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600',
    duration: '28h 10m',
    difficulty: 'Intermediate',
    rating: 4.5,
    reviewCount: 1023,
    enrolledCount: 7890,
    videoUrl: 'https://www.youtube.com/watch?v=ulprqHHWlng',
    lessons: [
      { title: 'Introduction to Cloud Computing', videoUrl: 'https://www.youtube.com/watch?v=ulprqHHWlng', duration: '18:30' },
      { title: 'AWS IAM & Security', videoUrl: 'https://www.youtube.com/watch?v=iF9fs8Rw4Uo', duration: '25:00' },
      { title: 'EC2 & Compute Services', videoUrl: 'https://www.youtube.com/watch?v=TsRBftzZsQo', duration: '40:20' },
      { title: 'S3 & Storage Solutions', videoUrl: 'https://www.youtube.com/watch?v=77lMCiiMilo', duration: '32:45' },
      { title: 'Serverless with Lambda', videoUrl: 'https://www.youtube.com/watch?v=eOBq__h4OJ4', duration: '38:10' },
    ],
    createdAt: new Date('2024-05-12'),
  },
  {
    id: 'course-006',
    title: 'Cybersecurity Essentials',
    description: 'Learn cybersecurity fundamentals including network security, cryptography, ethical hacking, vulnerability assessment, and incident response. Build skills for a career in infosec.',
    instructor: 'David Martinez',
    category: 'Cybersecurity',
    thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600',
    duration: '20h 45m',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviewCount: 756,
    enrolledCount: 5230,
    videoUrl: 'https://www.youtube.com/watch?v=hXSFdwIOfnE',
    lessons: [
      { title: 'Cybersecurity Landscape', videoUrl: 'https://www.youtube.com/watch?v=hXSFdwIOfnE', duration: '20:00' },
      { title: 'Network Security Basics', videoUrl: 'https://www.youtube.com/watch?v=E03gh1huvW4', duration: '35:30' },
      { title: 'Cryptography Fundamentals', videoUrl: 'https://www.youtube.com/watch?v=jhXCTbFnK8o', duration: '28:15' },
    ],
    createdAt: new Date('2024-06-01'),
  },
];
